apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
data:
  redis.conf: |
    # Redis configuration file
    bind 0.0.0.0
    protected-mode no
    port 6379
    appendonly yes
    dir /data
