apiVersion: v1
kind: Service
metadata:
  name: go-http-service
  labels:
    app: go-http-service-kind
    creation_method: serivice
    env: local
spec:
  selector:
    app: go-http-pod # same as deployment label
  ports:
    - name: http # use name connection port which you can change the por every time you want
      port: 9999
      targetPort: http
      nodePort: 30999 # 30000-32767 is the valid range !
  type: LoadBalancer
