apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-server
  labels:
    app: env-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-server
  template:
    metadata:
      name: env-server
      labels:
        app: env-server
    spec:
      containers:
        - name: env-server
          image: manouchehrrasouli96/env-server:v0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: env-config-map
                  key: APP_PORT
            - name: STAGE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: APP_SECRET_STAGE
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      