apiVersion: v1
kind: Pod
metadata:
  name: go-http-from-yml
  labels:
    creation_method: manual
    env: local
spec:
  nodeSelector: # specify that for that container we need a node that have gpu=true label added on it
    gpu: "true"
  containers:
    - image: manouchehrrasouli96/golang-http-server:0.0.1
      name: go-http-from-yml
      ports:
        - containerPort: 9999
          protocol: TCP